[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["streamlit (>=1.53.0,<2.0.0)", "segyio (>=1.9.14,<2.0.0)", "plotly (>=6.5.2,<7.0.0)", "rasterio (>=1.5.0,<2.0.0)"]
[tool.poetry]
package-mode = false
